Repository gboycdw/gaMeZone, pull requests merged in 2023-05, with the labels that each got.

#14 PR for branch protection test
  FrontEnd/src/pages/mainPage/main.tsx
Labels: documentation

#159 [Add] 로그아웃 기능 추가
  FrontEnd/src/pages/mainPage/main-footer.tsx
Labels: User

#177 [add] 마이페이지 닉네임 변경 API 추가
  BackEnd/README.md
  BackEnd/src/db/models/user-models.js
  BackEnd/src/middlewares/login-required.js
  BackEnd/src/routers/user-routers.js
  BackEnd/src/services/user-service.js
  FrontEnd/src/pages/myPage/components/profile.tsx
  FrontEnd/src/pages/myPage/nickname-change.tsx
  FrontEnd/src/pages/userPages/login.tsx
Labels: 서버, User, 클라이언트
